name: Android Tag CI

on:
  push:
    tags:
      - '*'

jobs:
  upload-apk:
    name: Generate APK and Upload artifact
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate APK
        run: bash ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
